services:
  main_server:
    build: . 
    container_name: main_server
    ports:
      -"8000:8000"
    environment:
      - SERVER_ROLE=main
    depends_on:
      - redis
  
  redis:
    image: redis:7
    container_name: redis
    ports:
      -"6379:6379"
  
  # rpi1:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile_for_rpi
  #   container_name: rpi1
  #   environment:
  #     - SERVER_ROLE=rpi
  #     - MAIN_SERVER_URL=http://main-server:8000
  #   ports:
  #     - "8101:8000"
  #   depends_on:
  #     - main_server

  # rpi2:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile_for_rpi
  #   container_name: rpi2
  #   environment:
  #     - SERVER_ROLE=rpi
  #     - MAIN_SERVER_URL=http://main-server:8000
  #   ports:
  #     - "8102:8000"
  #   depends_on:
  #     - main_server

  # rpi3:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile_for_rpi
  #   container_name: rpi3
  #   environment:
  #     - SERVER_ROLE=rpi
  #     - MAIN_SERVER_URL=http://main-server:8000
  #   ports:
  #     - "8103:8000"
  #   depends_on:
  #     - main_server