version: '3.8'
services:
  main_server:
    build: . 
    container_name: main_server
    ports:
      - "8000:8000"
    environment:
      - SERVER_ROLE=main
    depends_on:
      - redis
  
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
  
  prometheus:
    image : prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    depends_on:
      - node_exporter
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
  
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - loki
  loki:
    image: grafana/loki:2.8.2
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yml
    volumes:
      - ./loki-config.yml:/etc/loki/local-config.yml:ro
      - loki-data:/loki

  promtail:
    image: grafana/promtail:2.8.2
    container_name: promtail
    volumes:
      - /var/log:/var/log
      - ./promtail-config.yml:/etc/promtail/promtail-config.yml:ro
    command: -config.file=/etc/promtail/promtail-config.yml
    depends_on:
      - loki
  
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    ports: 
      - "9100:9100"
    restart: unless-stopped
    pid: "host"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro 

volumes:
  grafana-data:
  loki-data:


















  # rpi1:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile_for_rpi
  #   container_name: rpi1
  #   environment:
  #     - SERVER_ROLE=rpi
  #     - MAIN_SERVER_URL=http://main-server:8000
  #   ports:
  #     - "8101:8000"
  #   depends_on:
  #     - main_server

  # rpi2:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile_for_rpi
  #   container_name: rpi2
  #   environment:
  #     - SERVER_ROLE=rpi
  #     - MAIN_SERVER_URL=http://main-server:8000
  #   ports:
  #     - "8102:8000"
  #   depends_on:
  #     - main_server

  # rpi3:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile_for_rpi
  #   container_name: rpi3
  #   environment:
  #     - SERVER_ROLE=rpi
  #     - MAIN_SERVER_URL=http://main-server:8000
  #   ports:
  #     - "8103:8000"
  #   depends_on:
  #     - main_server